### ISSUE TITLE
看不懂fps的格式。。。

### ISSUE THREAD

**Issue by Zhu0junLi** [zhblue/freeproblemset#23]
请问fps里的append prepend分别是什么意思啊？
还有solution和template有什么区别吗？

**Comment by zhblue** [comment]
append是自动加在学生代码后面的代码，prepend是前面。
solution是给管理员、老师用的参考程序。
template是提交时直接给学生看的，用来做程序填空题的模板。

**Comment by Zhu0junLi** [comment]
懂了，谢谢！
